{{- $innerJobType := .Values.innerJobType | default "pytorch" -}}
{{- /*
  Volcano Job: svc plugin creates Headless Service automatically (with hostname/subdomain)
  PyTorchJob: needs manual Headless Service
*/}}
{{- if eq $innerJobType "pytorch" }}
{{- /* Headless Service for PyTorchJob DNS resolution */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "appwrapperjob.name" . }}
    chart: {{ template "appwrapperjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    createdBy: "AppWrapperJob"
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    release: {{ .Release.Name }}
    app: {{ template "appwrapperjob.name" . }}
  ports:
    - name: master-port
      port: {{ .Values.masterPort | default 23456 }}
      targetPort: {{ .Values.masterPort | default 23456 }}
      protocol: TCP
{{- end }}
